
import type { Metadata } from "next";
 
import "./globals.css";
import { ThemeProvider } from "@/components/Theme-provider";
import { LanguageProvider } from "@/components/LanguageContext";
import RtlWrapper from "@/components/RtlWrapper";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={` `}>
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <RtlWrapper>
              {children}
            </RtlWrapper>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
